apiVersion: v1
data:
  config.yaml: |
    startDelaySeconds: 0
    rules:
    - pattern: 'java.lang<type=Memory><HeapMemoryUsage><(used|committed|init|max)>'
      name: jvm_heap_bytes_$1
      help: JVM heap memory
      type: GAUGE
    - pattern: 'java.lang<type=Memory><NonHeapMemoryUsage><(used|committed|init|max)>'
      name: jvm_nonheap_bytes_$1
      help: JVM non-heap memory
      type: GAUGE
    - pattern: 'java.lang<type=GarbageCollector, name=(.*)><>Collection(Count|Time)'
      name: jvm_gc_$2_total
      labels:
        gc: $1
      help: JVM GC stats
      type: COUNTER
    - pattern: 'java.lang<type=Threading><>(ThreadCount|PeakThreadCount|DaemonThreadCount)'
      name: jvm_threads_$1
      help: JVM threads
      type: GAUGE
    - pattern: 'java.lang<type=MemoryPool, name=(.*)><Usage><(used|committed|init|max)>'
      name: jvm_pool_bytes_$2
      labels:
        pool: $1
      help: JVM memory pool
      type: GAUGE
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"startDelaySeconds: 0\nrules:\n- pattern: 'java.lang\u003ctype=Memory\u003e\u003cHeapMemoryUsage\u003e\u003c(used|committed|init|max)\u003e'\n  name: jvm_heap_bytes_$1\n  help: JVM heap memory\n  type: GAUGE\n- pattern: 'java.lang\u003ctype=Memory\u003e\u003cNonHeapMemoryUsage\u003e\u003c(used|committed|init|max)\u003e'\n  name: jvm_nonheap_bytes_$1\n  help: JVM non-heap memory\n  type: GAUGE\n- pattern: 'java.lang\u003ctype=GarbageCollector, name=(.*)\u003e\u003c\u003eCollection(Count|Time)'\n  name: jvm_gc_$2_total\n  labels:\n    gc: $1\n  help: JVM GC stats\n  type: COUNTER\n- pattern: 'java.lang\u003ctype=Threading\u003e\u003c\u003e(ThreadCount|PeakThreadCount|DaemonThreadCount)'\n  name: jvm_threads_$1\n  help: JVM threads\n  type: GAUGE\n- pattern: 'java.lang\u003ctype=MemoryPool, name=(.*)\u003e\u003cUsage\u003e\u003c(used|committed|init|max)\u003e'\n  name: jvm_pool_bytes_$2\n  labels:\n    pool: $1\n  help: JVM memory pool\n  type: GAUGE\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"adservice-jmx-config","namespace":"online-boutique"}}
  name: adservice-jmx-config
  namespace: online-boutique
