apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"PodMonitor","metadata":{"annotations":{},"labels":{"release":"prometheus-stack"},"name":"adservice-jmx","namespace":"monitoring"},"spec":{"namespaceSelector":{"matchNames":["online-boutique"]},"podMetricsEndpoints":[{"interval":"10s","path":"/metrics","port":"jmx-metrics"}],"selector":{"matchLabels":{"app":"adservice"}}}}
  labels:
    release: prometheus-stack
  name: adservice-jmx
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - online-boutique
  podMetricsEndpoints:
  - interval: 10s
    path: /metrics
    port: jmx-metrics
  selector:
    matchLabels:
      app: adservice
