apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: train-ticket-gateway
  namespace: train-ticket
spec:
  gatewayClassName: istio
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: trainticket-tls
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: train-ticket-route
  namespace: train-ticket
spec:
  parentRefs:
  - name: train-ticket-gateway
    port: 443
  hostnames:
  - train-ticket.younesnb.linkpc.net
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: ts-ui-dashboard
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: ts-ui-dashboard
      port: 8080
